apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Exchangerate
  namespace: core
  labels:
    product: exchange
    app: Exchangerate
    tier: backend
    phase: dev
    deployment: v1	
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        product: exchange
        app: Exchangerate
        tier: backend
        phase: dev
        deployment: v1
    spec:
      containers:
      - image: acreu2c002dev01.azurecr.io/bcp/Exchangerate:0.0.1
        name: Exchangerate
        imagePullPolicy: Always
        resources:
            requests:
              memory: "384Mi"
            limits:
              memory: "512Mi"
        env:
        - name: ambiente
          value: "dev"
        - name: version
          value: "0.0.1"
        - name: name
          value: "Exchangerate"
        - name: JAVA_OPTIONS
          value: "-Xms64m -Xmx128m"          
        - name: CONFIG_NO_SENSITIVE
          valueFrom:
            configMapKeyRef:
              name: Exchangerate-properties
              key: config-dev.properties
        - name: MESSAGE_CATALOG
          valueFrom:
            configMapKeyRef:
              name: message-catalog
              key: message-catalog.properties      
        - name: CONFIG_SENSITIVE
          valueFrom:
            secretKeyRef:
              name: config-sensibles
              key: config-sensibles-dev.properties
        volumeMounts:
        - mountPath: /data
          name: mdp-dev-volume
        - mountPath: /etc/localtime 
          name: tz-config  
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP 
      volumes:
      - name: mdp-dev-volume
        azureFile:
          secretName: storage-secret
          shareName: resources
          readOnly: false
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Lima    
      imagePullSecrets:
      - name: github-secret          